version: "3.9"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: hexapod-build
    container_name: hexapod-build
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
      - ./build:/home/node/app/build
    command: npm run build:client